name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist
      - name: Push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist
          git commit -m "Generated snake animation"
          git push
